name: Dataset idea
description: Template to walk a person through documenting a new dataset idea
title: "[IDEA] <title>"
labels: ["dataset", "Needs Triage"]
assignees: "sergegoussev"
body:
- type: markdown
  attributes:
    value: |

      Thank you for telling us about a new idea for the catalogue! 

      This guide will ask you a few questions to help us understand the dataset better. For context to the overall process of contribuing a dataset to the catalogue, check out the [guide on the reproducibility project site](https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/catalogue/contributing.html).

      ## Help us understand the dataset

- type: input
  id: dataset-name
  attributes:
    label: Dataset Name
    description: First off, how would you name this dataset?
    placeholder: ex. ABC-country-scanner-grocery-dataset
  validations:
    required: false
- type: input
  id: dataset-url
  attributes:
    label: Dataset Location
    description: Where can we find the dataset?
    placeholder: ex. https://www.zenodo.org/records/1234567
  validations:
    required: false
- type: input
  id: dataset-owner
  attributes:
    label: Dataset Owner
    description: Who owns this dataset? (e.g. is it you or if its another party, specify if you know)
    placeholder: ex. This is my dataset
  validations:
    required: false
- type: textarea
  id: dataset-description
  attributes:
    label: Tell us a bit about why you recommend this dataset
    description: Cover anything that would help us understand the dataset and the value it has to resaerchers in price statistics (if not obvious). 
    placeholder: Full scanner dataset from country ABC. Very long time series applicable for benchmarking multilateral methods.
  validations:
    required: true
- type: dropdown
  id: dataset-use
  attributes:
    label: Permissions/licence to use the dataset
    description: Do you know if this dataset can be used for research purposes? Do you know any limitations?
    options:
      - openly available
      - needs permission from owner
      - not currently open but the owner may be open to making it available
      - other/don't know
  validations:
    required: true
- type: markdown
  attributes:
    value: |

      ## Help us categorize the dataset

- type: dropdown
  id: dataset-type
  attributes:
    label: Dataset type
    description: How would you categorize the dataset?
    options:
      - web scraped dataset
      - scanner dataset
      - administrative dataset
      - field or sample dataset
      - other (specify below)
  validations:
    required: true
- type: input
  id: other-data-type
  attributes:
    label: Other data type
    description: If you specified 'other' above, please describe it here
  validations:
    required: false
- type: dropdown
  id: dataset-topic
  attributes:
    label: Dataset topic
    description: What main type of topic (in terms of COICOP categories or aspects being meaured) would you say it fits under?
    options:
      - electronics-and-applicances
      - housing
      - groceries-and-food
      - fuel
      - other (specify below)
  validations:
    required: true
- type: input
  id: other-data-topic
  attributes:
    label: Other data topic
    description: If you specified 'other' above, please describe it here
  validations:
    required: false
- type: markdown
  attributes:
    value: |

      ## Contact info

- type: input
  id: contact-me
  attributes:
    label: How can we contact you (outside of using this issue)?
    description: |
      We are going to respond to this issue when we process your request. However if you don't use GitHub often, please let us know how else we can contact you for any follow up.
    
      **NOTE**: Your email will be public (as it will be in the GitHub issue). If you would like to provide your email directly, please reach out to the [Project Team lead](https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/about.html#project-team-members).
    placeholder: ex. firstname.lastname@nso.org
  validations:
    required: false
