apiVersion: "v3.1.0"
kind: "DataContract"
id: "eurostat-seasonal-products-dataset"
version: "1.0"
status: "<b>Draft</b><br><a href='https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/catalogue/contributing.html#maturity-model'>Target documentation level</a>: 2"
name: "Eurostat seasonal products dataset"
description:
  purpose: |
    Dataset developed by Eurostat for the 'Guide on Multilateral Methods in the HICP' with seasonal data to help demonstrate multilateral methods
  limitations: |
    <i>APA style:</i> <br>Eurostat, & STATEC. (2022). Eurostat seasonal products dataset [Data set]. In Guide on multilateral methods in the Harmonised Index on Consumer Prices - 2022 edition. Eurostat. https://doi.org/10.5281/zenodo.19562039<br>
    <br>
    <i>Chicago style</i><br>Eurostat, and STATEC. “Eurostat Seasonal Products Dataset”. Guide on Multilateral Methods in the Harmonised Index on Consumer Prices - 2022 Edition. Eurostat, January 11, 2022. https://doi.org/10.5281/zenodo.19562039.<br>
    <br>
    <i>Bibtex citation</i><br><a href='https://raw.githubusercontent.com/UN-Task-Team-for-Scanner-Data/price-stats-data-catalogue/main/bitex/eurostat-seasonal.bib'>Click here for raw form</a>
  usage: |
    Open dataset, shared under "Creative Commons Attribution 4.0 International" licence on Zenodo. Originally published alongside the Guide on Multilateral Methods in the Harmonised Index on Consumer Prices (HICP).

    <br><br>
    <b>Links:</b><br>
    <ul>
      <li>Dataset: <a href='https://doi.org/10.5281/zenodo.19562039'>https://doi.org/10.5281/zenodo.19562039</a></li>
      <li>Manual dataset used in: <a href='https://doi.org/10.2785/873932'>Guide on multilateral methods in the Harmonised Index on Consumer Prices (2022)</a></li>
    </ul>
  # TO DO: review and test later. Commented out as this does not render by datacontract-cli with the current version
  # authoritativeDefinitions: 
  #   - type: "Dataset zenodo record"
  #     url: "https://www.ilo.org/sites/default/files/wcmsp5/groups/public/@dgreports/@stat/documents/presentation/wcms_331153.pdf"
  #     description: "CPI Manual version"
domain: "Consumer Price Statistics"
tenant: "Eurostat"
tags:
  - "scanner"
  - "groceries-and-food"
schema:
  - name: "Dataset"
    businessName: ""
    description: |
      An artifical data set  with 201 price observations for 36 periods and 12 products
    type: "object"
    properties:
      - name: "Period"
        logicalType: "object"
        description: |
          Time period, represented as an integer from 1 to 36.
        examples:
          - "1"
        businessName: "Period number"
      - name: "Product"
        logicalType: "object"
        description: "The Product name"
        examples:
          - "A"
        businessName: "Product name"
      - name: "Turnover"
        logicalType: "number"
        description: |
          The turnover of the data.
        examples:
          - "642.49"
        businessName: "Turnover"  
      - name: "Quantity"
        logicalType: "number"
        description: |
          The number of products sold.
        examples:
          - "88.088"
        businessName: "Quantity"
      - name: "Price"
        logicalType: "number"
        description: |
          The unit price of each sold product.
        examples:
          - "2.09964"
        businessName: "Price"
